### ISSUE TITLE
CEH to share additional source of UK moth images

### ISSUE THREAD

**Issue by KatrionaGoldmann** [AMI-trap/AMI-trap-org#4]
- [ ] send csv with image label and URL

**Comment by DavidRoy** [comment]
[uk_images_data_moths_2023-08-22.zip](https://github.com/AMI-trap/AMI-trap-org/files/12410666/uk_images_data_moths_2023-08-22.zip)

Use preferred_taxon for building the classifier.  Taxon_full_name is the name entered which could be a common name or a synonym (i.e. an old scientific name).  ~500k images, all reviewed by an expert

SQL for reference:
select case when om.path like 'http%' then om.path else concat('https://warehouse1.indicia.org.uk/upload/', om.path) end image_url,
	l.code as image_licence,
	concat('UK_iRecord:', o.id) as observation_id,
	concat('UK_iRecord:', om.id) as image_id,
	concat('UK_iRecord:', ttl.taxon_id) as taxon_id_at_source,
	concat('UK_UKSI:',ttl.external_key) as taxon_id_external_key,
	ttl.family_taxon,
	ttl.taxon as taxon_full_name,
	ttl.preferred_taxon,
	ttl.preferred_authority,
	conf.attr_sex as sex,
	conf.attr_stage as morph
from cache_occurrences_functional o
	left join occurrence_media om on o.id = om.occurrence_id
	left join cache_taxa_taxon_lists ttl on o.taxa_taxon_list_id = ttl.id
	left join cache_occurrences_nonfunctional conf on o.id = conf.id
	left join licences l on om.licence_id = l.id
where om.path is not null
	and o.record_status = 'V' -- verified records only
	and o.date_type = 'D' -- to remove date ranges
	and o.website_id IN (3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 23, 24, 25, 27, 29, 30, 32, 33, 34, 40, 41, 42, 43, 44, 47, 49, 51, 65, 68, 69, 71, 72, 73, 75, 87, 88, 92, 94, 95, 97, 98, 101, 108, 115, 116, 120, 121, 123, 124, 126, 131, 135, 137, 139, 141, 142, 143, 145, 147, 148) -- websites that share for reporting, iNaturalist excluded
	and om.media_type_id = 3744 -- Only return images
	and om.deleted = false
	and o.media_count >= 1 -- where occurrences have images
	and ttl.taxon_list_id = 15 -- only uksi
        and ttl.taxon_group_id = 114 -- restrict to 'insect - moths'
	and ttl.taxon_rank_id = 26 -- Only return species

**Comment by DavidRoy** [comment]
If you want to restrict to larger (macro) moths, filter by these families.  The classifer will struggle from moths from other families (micro-moths)

Cossidae
Drepanidae
Endromidae
Erebidae
Geometridae
Hepialidae
Lasiocampidae
Limacodidae
Noctuidae
Nolidae
Notodontidae
Saturniidae
Sesiidae
Sphingidae
Zygaenidae
